name: CI/CD Workflow

on: ['push']

jobs:
  display-my-name:
    runs-on: ubuntu-latest
    steps:
      - name: Display my name
        run: echo "Hello Sasi Kanth"
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Running Few Shell Commands
        run: |
          hostname
          echo "$SHELL"
          date
          uptime
          ls -l /
          cat /etc/hosts
        shell: sh