name: CI/CD Pipelines

on: ['push']

jobs:
  execute-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: display message
        run: echo "Hello Sasi"
      - name: runs multiple commands
        run: |
          hostname
          uptime
          date
          uname -a
          ls -l /