name: CI/CD Workflow
#Running 3 jobs here, Def shell in windows is Powershell, and we can use bash as well in windows.
#
on: ['push']

jobs:
  display-my-name:
    runs-on: ubuntu-latest
    steps:
      - name: Display my name
        run: echo "Hello Sasi Kanth"
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Running Few Shell Commands
        run: |
          hostname
          ps -p $$
          date
          uptime
          ls -l /
          cat /etc/hosts
        shell: sh
  run-powershell-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps:
      - name: Working Dir
        run: Get-Location
      - name: Run Bash shell
        run: pwd
        shell: bash
# Jobs will run parallelly, if we have a dependency like after completion of one job the other should start, in that case we will fallow like below.
# needs[] key, we can mention the job names in needs[] array, then once the mentioned jobs complete, then only the other jobs will run. 