name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        echo "Hello World"
      - name: display hostname
        run: |
          hostname
          date
          uname -a
          uptime
