name: CI/CD Workflow
#Running 3 jobs here, Def shell in windows is Powershell, and we can use bash as well in windows.
#
on: ['push']

jobs:
  display-my-name:
    runs-on: ubuntu-latest
    steps:
      - name: Display my name
        run: echo "Hello Sasi Kanth"
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Running Few Shell Commands
        run: |
          hostname
          ps -p $$
          date
          uptime
          ls -l /
          cat /etc/hosts
        shell: sh
  run-powershell-commands:
    runs-on: windows-latest
    steps:
      - name: Working Dir
        run: Get-Location
      - name: Run Bash shell
        run: pwd
        shell: bash