name: Sample Workflow

on: [push]

jobs:
  run-shell-command:
    runs-on: centos-latest
    steps:
      - name: Print Message
        run: echo "First Workflow Job"
      - name: multiple commands
        run: |
          hostname
          cat /etc/passwd
          cat /etc/hosts
          uptime