name: actions-job

on: ["push"]

jobs:
  run-actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone a template
        id: justGreet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: SasiKanthAkula
      - name: Display message
        run: echo "${{ steps.justGreet.outputs.time }}"


