#temp-space for Practice:

name: Product Release

on: ["push"]

jobs:
  get-system-arch:
    runs-on: ubuntu-latest
    steps:
      - name: display hostname and copy to my-hosts file
        run: |
          echo `hostname` > /etc/myhostname
          date
  display-host-name-from-file:
    needs: get-system-arch
    runs-on: ubuntu-latest
    steps:
      - name: display file content for hostname
        run: cat /etc/hosts