#temp-space for Practice:

name: Product Release

on: ["push"]

jobs:
  get-system-arch:
    runs-on: ubuntu-latest
    steps:
      - name: display hostname and copy to my-hosts file
        run: |
          echo `hostname` > myhostname
          date
          cat myhostname
  display-host-name-from-file:
    needs: get-system-arch
    runs-on: ubuntu-latest
    steps:
      - name: display file content for hostname
        run: cat /etc/hosts

#There are few predefined templates which does some actions for us. we can find them here: https://github.com/actions.
#In the above example, we are just calling a template which Greets a person.
#We can call with branch/version/commit id. ie,  
#actions/hello-world-javascript-action@v1.1 (or)
#actions/hello-world-javascript-action@master (or)
#actions/hello-world-javascript-action@       
