#temp-space for Practice:

name: CI/CD

on: ["push"]

jobs:
  run-temp-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Display Date & Time
        run: date
      - name: Print system arc and other details
        run: |
          uname -a
          ls -l /
  run-dependant-job:
    runs-on: ubuntu-latest
    needs: "run-temp-shell-commands"
    steps:
      - name: wait for previous
        run: |
          pwd
          echo "Test After aboce job completes"
        

