name: test-actions-job

on: ["push"]

jobs:
  pull-templates:
    runs-on: ubuntu-latest
    steps:
      - name: clone a repo
        id: greetings
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: SasiKanthAkula
      - name: Display my name
        run: echo "{{ steps.greetings.outputs }}"
